[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NPM_FLAGS = "--version"
  NODE_VERSION = "18"
  NEXT_PRIVATE_STANDALONE = "true"

# Configuration pour Prisma
[[plugins]]
  package = "@netlify/plugin-nextjs"

[context.production]
  command = "rm -rf .next && rm -rf node_modules/.cache && npx prisma generate && npm run build"

[context.deploy-preview]
  command = "rm -rf .next && rm -rf node_modules/.cache && npx prisma generate && npm run build"

[context.branch-deploy]
  command = "rm -rf .next && rm -rf node_modules/.cache && npx prisma generate && npm run build"
